app/problem/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextAreaField, TextField, SelectField, HiddenField, IntegerField
from wtforms.validators import DataRequired, Length
from wtforms import ValidationError
from ..models import Language


class SubmitForm(Form):
    language = SelectField('Language', coerce=int, choices=Language.CHOICES)
    code = HiddenField('Code')
    submit = SubmitField('Submit')


class AddTopicForm(Form):
    problem =IntegerField('Problem')
    title = StringField('Title')
    content = TextAreaField('Content')
    submit = SubmitField('Submit')


class ReplyForm(Form):
    content = TextAreaField('Content')
    submit = SubmitField('Submit')

app/problem/__init__.py
from flask import Blueprint

problem = Blueprint('problem', __name__)

from . import views, forms

app/problem/views.py
from flask import render_template, redirect, request, url_for, flash, current_app, abort
from flask.ext.login import login_required, current_user
from . import problem
from .. import db
from ..models import User, Problem, Submission, Language, News, Topic, Reply, Permission
from .forms import SubmitForm, ReplyForm, AddTopicForm




@problem.route('/', methods=['GET', 'POST'])
def list():
    page = request.args.get('page', 1, type=int)
    if current_user.can(Permission.PUBLISH_PROBLEM):
        pagination = Problem.query.order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else:
        pagination = Problem.query.filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    problems = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/list.html', problems=problems, pagination=pagination, newslist=newslist)





@problem.route('/search', methods=['GET', 'POST'])
def search():
    page = request.args.get('page', 1, type=int)
    key = request.args.get('key', '')
    type = request.args.get('type', '')
    print "key == ", key, "  ", "type == ", type
    if key == None or key == "":
        return redirect(url_for("problem.list"))
    if type == None or type == "":
        return redirect(url_for("problem.list"))
    if int(type) == 0:
        pagination = Problem.query.filter(Problem.id==int(key)).filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else :
        pagination = Problem.query.filter(Problem.title.like("%" + key + "%")).filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )

    problems = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/search_list.html', problems=problems, pagination=pagination, newslist=newslist)



@problem.route('/<id>', methods=['GET', 'POST'])
def show(id):
    problem = Problem.query.filter_by(id=id).first()
    if problem.visible == False and (not current_user.can(Permission.PUBLISH_PROBLEM)):
        return render_template('no_permission.html')
    form = SubmitForm()
    #form.language.data = current_user.default_language
    if form.validate_on_submit():
        #submission = Submission()
        # print "language:", form.language.data
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/problem.html', problem=problem, form=form)
        # print form.code.data
        # print "len == ", len(form.code.data)
        submission = Submission(language=form.language.data, code=form.code.data,
                                problem=Problem.query.filter_by(id=id).first(),
                                shared=False, code_length=len(form.code.data),
                                user=current_user
        )
        db.session.add(submission)
        db.session.commit()
        current_user.total_submit = current_user.total_submit + 1
        problem.total_submited = problem.total_submited + 1

        return redirect(url_for('status.list'))
    #form.language.data = 0
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/problem.html', problem=problem, form=form, newslist=newslist)



@problem.route('/code/<id>', methods=['GET', 'POST'])
def show_code(id):
    submission = Submission.query.filter_by(id=id).first()
    if (not current_user.is_administrator) and (submission.user != current_user):
        abort(403)

    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('status/code.html', submission=submission, newslist=newslist)


@problem.route('/<id>/discuss', methods=['GET', 'POST'])
def show_topics(id):
    problem = Problem.query.filter_by(id=id).first()
    # topics = problem.topics
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/topics.html', problem=problem, newslist=newslist)



@problem.route('/<id>/add_topic', methods=['GET', 'POST'])
def add_topic(id):
    problem = Problem.query.filter_by(id=id).first()
    form = AddTopicForm()
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    if form.validate_on_submit():
        problem = Problem.query.filter_by(id=form.problem.data).first()
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/add_topic.html', form=form, problem=problem, newslist=newslist)
        topic = Topic(title=form.title.data, content=form.content.data,
                        problem=problem, user=current_user)
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('problem.show_topic', id=problem.id, tid=topic.id))
    return render_template('problem/add_topic.html', form=form, problem=problem, newslist=newslist)



@problem.route('/<id>/discuss/<tid>', methods=['GET', 'POST'])
def show_topic(id, tid):
    problem = Problem.query.filter_by(id=id).first()
    topic = Topic.query.filter_by(id=tid).first()
    print topic
    # topics = problem.topics
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    form = ReplyForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)
        if not current_user.can(Permission.REPLY):
            flash("no permissions")
            return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)
        reply = Reply(content=form.content.data, user=current_user, is_delete=0, topic=topic)
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('problem.show_topic', id=problem.id, tid=topic.id))
    return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)

app/templates/problem/add_topic.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem show{% endblock %}

{% block page_content %}
<div class="container problem_content">
    <div class="row">
        <div class="col-md-9">

            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ problem.title }}
                    </div>
                    <div class="panel-body">
                        <!-- body -->
                         {{ wtf.quick_form(form) }}
                    </div>
                </div>



            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}

app/templates/problem/list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem List{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Problem list</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group form-inline">
                            <form name="search_form" method="get" action="search">
                                <label for="key">Search:</label>
                                <input class="form-control" name="key" id="key"/>
                                <label >In:</label>
                                <select class="form-control" id="type" name="type"><option selected="" value="0">ID</option><option value="1">Title</option></select>
                                <button class="btn btn-default" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th width="60%">Name</th>
                                <th width="15%">Difficulty</th>
                                <th width="20%">AC/Submit</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for problem in problems %}
                            <tr>
                                <th scope="row">{{ problem.id }}</th>
                                <td><a href="{{ url_for('problem.show', id=problem.id) }}">{{ problem.title }}</a></td>
                                <td>{{ macros.problem_difficulty(problem) }}</td>
                                <td>{{ problem.total_accepted }}/{{ problem.total_submited }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <nav>
                            {% if pagination %}
                            <div class="pagination">
                                {{ macros.pagination_widget(pagination, 'problem.list') }}
                            </div>
                            {% endif %}
                        </nav>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>

{% endblock %}

app/templates/problem/problem.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem show{% endblock %}

{% block page_content %}
<div class="container problem_content">
    <div class="row">
        <div class="col-md-9">

            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ problem.title }}

                        {% if current_user.is_moderator %}
                        <a href="{{ url_for('dashboard.edit_problem', id=problem.id) }}">edit</a>{% endif %}

                        <a href="{{ url_for('problem.show_topics', id=problem.id) }}">discuss</a>
                    </div>
                    <div class="panel-body">
                        <!-- body -->
                        <div id="tl-problem-content">
                            <div class="limit">
                                <div>时间限制:<span style="margin-left: 10px;">{{ problem.time_limit }}ms</span></div>
                                <!--<div>单点时限:<span style="margin-left: 10px;">1000ms</span></div>-->
                                <div>内存限制:<span style="margin-left: 10px;">{{ problem.memory_limit }}mb</span></div>
                            </div>
                            <table></table>
                            <dl class="des">
                                <div><h3>描述</h3>
                                    {{ problem.pro_desc|safe }}
                                </div>
                                <div><h3>输入</h3>
                                    <pre>{{ problem.pro_input }}</pre>
                                </div>
                                <div><h3>输出</h3>
                                    <pre>{{ problem.pro_output }}</pre>
                                </div>
                                <dt>样例输入</dt>
                                <dd>
                                    <pre>{{ problem.sample_input }}</pre>
                                </dd>
                                <dt>样例输出</dt>
                                <dd>
                                    <pre>{{ problem.sample_output }}</pre>
                                </dd>
                            </dl>
                        </div>
                        <!-- end body -->
                    </div>
                </div>
                <!--{{ wtf.quick_form(form) }}-->
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading">code editor</div>
                        <div class="panel-body">
                            <!-- body -->
                            <div class="code-editor" id="code-editor">
                                <form class="form-horizontal panel-body" method="post" action="">
                                    {{ form.csrf_token }}


                                    {{form.language.label(class_='col-sm-2 control-label')}}
                                    {{ form.language(class_='form-control', placeholder=form.language.description) }}
                                    <hr>
                                    {{ form.code(class_='form-control', placeholder=form.code.description) }}
                                    <div id="editor" name="editor"></div>


                                    <div class="form-group">
                                        <div class="col-sm-offset-10 col-sm-10">
                                            <button class="btn btn-primary" id="submitbtn">submit</button>
                                        </div>
                                    </div>
                                </form>
                                <!--<script src="http://cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js" type="text/javascript" charset="utf-8"></script>-->
                                <script>
                                          var editor = ace.edit("editor");
                                          editor.getSession().setMode("ace/mode/c_cpp");

                                          var eventOne = function(){
                                              document.getElementById("code").value=editor.getValue();
                                              //alert("hehe");
                                            }
                                          var btn = document.getElementById("submitbtn");
                                            btn.onclick = eventOne;
                                          console.log(btn);



                                </script>
                            </div>
                            <!-- end body -->
                        </div>
                    </div>


                    <!--<div id="editor">some text</div>-->
                    <!--<script src="http://cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js" type="text/javascript" charset="utf-8"></script>-->


                    <!-- <hr> -->
                </div>

            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>

<!--{{ wtf.quick_form(form) }}-->
{% endblock %}

app/templates/problem/search_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem List{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Problem list</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group form-inline">
                            <form name="search_form" method="get" action="{{ url_for('problem.search') }}">
                                <label for="key">Search:</label>
                                <input class="form-control" name="key" id="key"/>
                                <label >In:</label>
                                <select class="form-control" id="type" name="type"><option selected="" value="0">ID</option><option value="1">Title</option></select>

                                <button class="btn btn-default" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th width="60%">Name</th>
                                <th width="15%">Difficulty</th>
                                <th width="20%">AC/Submit</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for problem in problems %}
                            <tr>
                                <th scope="row">{{ problem.id }}</th>
                                <td><a href="{{ url_for('problem.show', id=problem.id) }}">{{ problem.title }}</a></td>
                                <td>{{ macros.problem_difficulty(problem) }}</td>
                                <td>{{ problem.total_accepted }}/{{ problem.total_submited }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <nav>
                            {% if pagination %}
                            <div class="pagination">
                                {{ macros.pagination_widget(pagination, 'problem.search', key=request.args['key'], type=request.args['type']) }}
                            </div>
                            {% endif %}
                        </nav>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>

{% endblock %}

app/templates/problem/topic.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem show{% endblock %}

{% block page_content %}
<div class="container problem_content">
    <div class="row">
        <div class="col-md-9">

            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ problem.title }}
                    </div>
                    <div class="panel-body">
                        {{ topic.content }}

                    </div>
                </div>
                <div class="panel panel-default">
                <div class="panel-heading">回复
                </div>
                <div class="panel-body">
                    {% for reply in topic.replys %}
                    <div  class="cell">

                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <tbody>
                            <tr>
                                <td width="48" valign="top" align="center">
                                    <a href="{{ url_for('account.show', id=reply.user.id) }}">
                                    <image src="{{ reply.user.avatar(46) }}"
                                           alt="avatar"></image>
                                    </a>
                                </td>
                                <td width="10" valign="top"></td>
                                <td width="auto" valign="top" align="left">
                                    <strong><a href="{{ url_for('account.show', id=reply.user.id) }}" class="dark">{{ reply.user.username }}</a></strong>&nbsp; &nbsp;
                                    <div class="reply_content">
                                        {{ reply.content }}
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <hr>
                    </div>
                    {% endfor %}

                </div>


            </div>

                {{ wtf.quick_form(form) }}



            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}

app/templates/problem/topics.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Problem show{% endblock %}

{% block page_content %}
<div class="container problem_content">
    <div class="row">
        <div class="col-md-9">

            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ problem.title }}
                        <a href="{{ url_for('problem.add_topic', id=problem.id) }}">post</a>
                    </div>
                    <div class="panel-body">

                        <!-- body -->
                         {% for topic in problem.topics %}
                                <div class="single_topic">
                                    <a href="{{ url_for('problem.show_topic', id=problem.id, tid=topic.id) }}" class="topic_title"><strong>{{ topic.title }}</strong></a>
                                    <a href="{{ url_for('account.show', id=topic.user.id) }}" class="topic_owner">{{ topic.user.username }}</a>
                                    <span class="topic_time">{{ topic.create_time }}</span>
                                </div>

                        {% endfor %}
                        <!-- end body -->
                    </div>
                </div>



            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}