app/contest/__init__.py
from flask import Blueprint

contest = Blueprint('contest', __name__)

from . import views, forms

app/contest/views.py
from flask import render_template, redirect, request, url_for, flash, current_app, abort, session
from flask.ext.login import login_user, logout_user, login_required, current_user
from . import contest
from .forms import AddContestForm, SubmitForm, AddTopicForm, ReplyForm, PasswordForm
from .. import db
from ..models import User, Contest, Problem, Contest_problem, Submission, Topic, Reply, Permission
import datetime
import time
from ..decorators import mod_required, admin_required
from datetime import datetime
import json

def check_contest_access(cid):
    # print "is_admin", current_user.is_administrator
    if current_user.is_administrator:
        return True
    contest = Contest.query.filter_by(id=cid).first()
    if contest.user == current_user:
        return True

    if contest.visible == False and not current_user.can(Permission.PUBLISH_NEWS):
        return False

    if contest.type == 0:
        return True

    if not current_user.have_access_to(1, cid):
        return False


@contest.route('/passwd/<cid>', methods=['GET', 'POST'])
def password(cid):
    print "to password"
    contest = Contest.query.filter_by(id=cid).first()
    form = PasswordForm()
    if form.validate_on_submit():
        if form.password.data == contest.password:
            cstr = 'contest' + str(cid)
            session[cstr] = True
            return redirect(url_for('contest.show', cid = cid))
        else:
            return render_template('contest/need_password.html', contest=contest, form=form)
    return render_template('contest/need_password.html', contest=contest, form=form)


@contest.route('/nopermission/<cid>', methods=['GET', 'POST'])
def nopermission(cid):
    contest = Contest.query.filter_by(id=cid).first()
    # form = PasswordForm()
    # if form.validate_on_submit():
    #     if form.password.data == contest.password:
    #         cstr = 'contest' + str(cid)
    #         session[cstr] = True
    #         return redirect(url_for('contest.show', cid = cid))
    #     else:
    #         return render_template('contest/need_password.html', contest=contest, form=form)
    return render_template('contest/nopermission.html', contest=contest)



@contest.route('/', methods=['GET', 'POST'])
def list():
    page = request.args.get('page', 1, type=int)

    if current_user.can(Permission.PUBLISH_NEWS):
        pagination = Contest.query.order_by(Contest.id.desc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else:
        pagination = Contest.query.filter_by(visible=True).order_by(Contest.id.desc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )

    contests = pagination.items
    return render_template('contest/list.html', contests=contests, pagination=pagination)



@contest.route('/search', methods=['GET', 'POST'])
def search():
    page = request.args.get('page', 1, type=int)
    key = request.args.get('key', '')
    type = request.args.get('type', '')
    print "key == ", key, "  ", "type == ", type
    if key == None or key == "":
        return redirect(url_for("contest.list"))
    if type == None or type == "":
        return redirect(url_for("contest.list"))
    if int(type) == 0:
        pagination = Contest.query.filter(Contest.title.like("%" + key + "%")).order_by(Contest.id.desc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else :
        user = User.query.filter_by(nickname=key).first()
        if user == None:
            return redirect(url_for("contest.list"))

        pagination = Contest.query.filter_by(user=user).order_by(Contest.id.desc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
        # print pagination.items

    contests = pagination.items
    return render_template('contest/search_list.html', contests=contests, pagination=pagination)





@contest.route('/add_contest', methods=['GET', 'POST'])
@login_required
@admin_required
def add_contest():
    form = AddContestForm()
    # print "start :", form.start_time.data
    # print "end :", form.end_time.data
    # if form.is_submitted():
    #     print "submitted"
    # if form.validate():
    #     print "valid"
    # print form.errors
    # print "start :", form.start_time.data
    # print "end :", form.end_time.data
    # form.problem_list.data = "{'Singleproblem':[{'id':1000, 'title':'xxxxx'}, {'id':1001, 'title':'yyyyy'}]}";
    # print "start time == ", form.start_time.data
    if form.validate_on_submit():
        print form.problem_list.data
        problems = json.loads(form.problem_list.data)
        # print int(problems[0]['id'])
        contest = Contest(title=form.title.data, start_time=form.start_time.data, end_time=form.end_time.data,
                          type=form.type.data, password=form.password.data, visible=form.visible.data,
                          user=current_user)
        db.session.add(contest)
        db.session.commit()

        pos = 1
        for data in problems:
            problem = Problem.query.filter_by(id=int(data['id'])).first()
            if problem == None:
                break
            title = data['name']
            if title == None:
                title = problem.title
            cp = Contest_problem(problem=problem, contest=contest, title=title, id=pos)
            pos += 1
            db.session.add(cp)
            db.session.commit()


        return redirect(url_for('contest.show', cid=contest.id))
    form.start_time.data = datetime.now()
    form.end_time.data = datetime.now()
    return render_template('contest/add_contest.html', form=form)


@contest.route('/<cid>', methods=['GET', 'POST'])
@login_required
# @can_access
def show(cid):
    flag = check_contest_access(cid)
    if flag == False:
        return redirect(url_for('contest.nopermission', cid=cid))
    # current_user.have_access_to2(cid)
    contest = Contest.query.filter_by(id=cid).first()
    return render_template('contest/contest.html', contest=contest)



@contest.route('/<cid>/problem/<pid>', methods=['GET', 'POST'])
def show_problem(cid, pid):
    flag = check_contest_access(cid)
    if flag == False:
        return redirect(url_for('contest.nopermission', cid=cid))
    # problem = Problem.query.filter_by(id=id).first()
    # return render_template('contest/problem.html',)
    contest = Contest.query.filter_by(id=cid).first()

    if contest.status == 0:
        return redirect(url_for('contest.show', cid=contest.id))

    cb = Contest_problem.query.filter_by(cid=cid).filter_by(id=pid).first()
    form = SubmitForm()
    problem = Problem.query.filter_by(id=cb.pid).first()
    now = datetime.now()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('contest/problem.html', cb=cb, form=form, contest=contest)

        if now > contest.end_time:
            flash('contest end')
            return render_template('contest/problem.html', cb=cb, form=form, contest=contest, problem=problem)

        if now < contest.start_time:
            flash('contest not start')
            return render_template('contest/problem.html', cb=cb, form=form, contest=contest, problem=problem)
        problem.total_submited += 1
        current_user.total_submit += 1
        submission = Submission(language=form.language.data, code=form.code.data,
                                contest_id=cid,
                                problem=problem,
                                shared=False,
                                user=current_user,
                                code_length=len(form.code.data)
        )
        db.session.add(submission)
        db.session.commit()
        return redirect(url_for('contest.status', cid=cid))
    return render_template('contest/problem.html', cb=cb, form=form, contest=contest, problem=problem)



@contest.route('/<cid>/status', methods=['GET', 'POST'])
def status(cid):
    flag = check_contest_access(cid)
    if flag == False:
        return redirect(url_for('contest.nopermission', cid=cid))
    contest = Contest.query.filter_by(id=cid).first()

    if contest.status == 0:
        return redirect(url_for('contest.show', cid=contest.id))

    page = request.args.get('page', 1, type=int)
    pagination = Submission.query.filter_by(contest_id=cid).order_by(Submission.id.desc()).paginate(
        page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
        error_out=False
    )
    submissions = pagination.items
    # print submissions
    #newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('contest/status.html', submissions=submissions, pagination=pagination, contest=contest)



@contest.route('/<cid>/topics', methods=['GET', 'POST'])
def topics(cid):
    flag = check_contest_access(cid)
    if flag == False:
        return redirect(url_for('contest.nopermission', cid=cid))

    contest = Contest.query.filter_by(id=cid).first()

    if contest.status == 0:
        return redirect(url_for('contest.show', cid=contest.id))

    # topics = contest.topics
    return render_template('contest/topics.html', contest=contest)



# id = db.Column(db.Integer, primary_key=True)
#     title = db.Column(db.String(64))
#     content = db.Column(db.Text())
#     create_time = db.Column(db.DateTime, default=datetime.utcnow, index=True)
#     user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
#     contest_id = db.Column(db.Integer, db.ForeignKey('contest.id'))
#     problem_id = db.Column(db.Integer, db.ForeignKey('problem.id'))
#     is_delete = db.Column(db.Boolean, default=False)
#     replys = db.relationship('Reply', backref='topic')

@contest.route('/<cid>/add_topic', methods=['GET', 'POST'])
def add_topic(cid):

app/problem/__init__.py
from flask import Blueprint

problem = Blueprint('problem', __name__)

from . import views, forms

app/problem/views.py
from flask import render_template, redirect, request, url_for, flash, current_app, abort
from flask.ext.login import login_required, current_user
from . import problem
from .. import db
from ..models import User, Problem, Submission, Language, News, Topic, Reply, Permission
from .forms import SubmitForm, ReplyForm, AddTopicForm




@problem.route('/', methods=['GET', 'POST'])
def list():
    page = request.args.get('page', 1, type=int)
    if current_user.can(Permission.PUBLISH_PROBLEM):
        pagination = Problem.query.order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else:
        pagination = Problem.query.filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    problems = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/list.html', problems=problems, pagination=pagination, newslist=newslist)





@problem.route('/search', methods=['GET', 'POST'])
def search():
    page = request.args.get('page', 1, type=int)
    key = request.args.get('key', '')
    type = request.args.get('type', '')
    print "key == ", key, "  ", "type == ", type
    if key == None or key == "":
        return redirect(url_for("problem.list"))
    if type == None or type == "":
        return redirect(url_for("problem.list"))
    if int(type) == 0:
        pagination = Problem.query.filter(Problem.id==int(key)).filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )
    else :
        pagination = Problem.query.filter(Problem.title.like("%" + key + "%")).filter_by(visible=True).order_by(Problem.id.asc()).paginate(
            page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
            error_out=False
        )

    problems = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/search_list.html', problems=problems, pagination=pagination, newslist=newslist)



@problem.route('/<id>', methods=['GET', 'POST'])
def show(id):
    problem = Problem.query.filter_by(id=id).first()
    if problem.visible == False and (not current_user.can(Permission.PUBLISH_PROBLEM)):
        return render_template('no_permission.html')
    form = SubmitForm()
    #form.language.data = current_user.default_language
    if form.validate_on_submit():
        #submission = Submission()
        # print "language:", form.language.data
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/problem.html', problem=problem, form=form)
        # print form.code.data
        # print "len == ", len(form.code.data)
        submission = Submission(language=form.language.data, code=form.code.data,
                                problem=Problem.query.filter_by(id=id).first(),
                                shared=False, code_length=len(form.code.data),
                                user=current_user
        )
        db.session.add(submission)
        db.session.commit()
        current_user.total_submit = current_user.total_submit + 1
        problem.total_submited = problem.total_submited + 1

        return redirect(url_for('status.list'))
    #form.language.data = 0
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/problem.html', problem=problem, form=form, newslist=newslist)



@problem.route('/code/<id>', methods=['GET', 'POST'])
def show_code(id):
    submission = Submission.query.filter_by(id=id).first()
    if (not current_user.is_administrator) and (submission.user != current_user):
        abort(403)

    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('status/code.html', submission=submission, newslist=newslist)


@problem.route('/<id>/discuss', methods=['GET', 'POST'])
def show_topics(id):
    problem = Problem.query.filter_by(id=id).first()
    # topics = problem.topics
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('problem/topics.html', problem=problem, newslist=newslist)



@problem.route('/<id>/add_topic', methods=['GET', 'POST'])
def add_topic(id):
    problem = Problem.query.filter_by(id=id).first()
    form = AddTopicForm()
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    if form.validate_on_submit():
        problem = Problem.query.filter_by(id=form.problem.data).first()
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/add_topic.html', form=form, problem=problem, newslist=newslist)
        topic = Topic(title=form.title.data, content=form.content.data,
                        problem=problem, user=current_user)
        db.session.add(topic)
        db.session.commit()
        return redirect(url_for('problem.show_topic', id=problem.id, tid=topic.id))
    return render_template('problem/add_topic.html', form=form, problem=problem, newslist=newslist)



@problem.route('/<id>/discuss/<tid>', methods=['GET', 'POST'])
def show_topic(id, tid):
    problem = Problem.query.filter_by(id=id).first()
    topic = Topic.query.filter_by(id=tid).first()
    print topic
    # topics = problem.topics
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    form = ReplyForm()
    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash('please login first')
            return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)
        if not current_user.can(Permission.REPLY):
            flash("no permissions")
            return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)
        reply = Reply(content=form.content.data, user=current_user, is_delete=0, topic=topic)
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('problem.show_topic', id=problem.id, tid=topic.id))
    return render_template('problem/topic.html', problem=problem, topic=topic, newslist=newslist, form=form)

app/ranks/__init__.py
from flask import Blueprint

ranks = Blueprint('ranks', __name__)

from . import views, forms

app/ranks/views.py
from flask import render_template, redirect, request, url_for, flash, current_app
from flask.ext.login import login_required, current_user
from . import ranks
from .. import db
from ..models import User, Problem, Submission, Language, News


@ranks.route('/', methods=['GET', 'POST'])
def list():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.total_accept.desc()).paginate(
        page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
        error_out=False
    )
    ranks = pagination.items
    #print ranks
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('ranks/list.html', ranks=ranks, pagination=pagination, newslist=newslist, start=current_app.config['OJ_PROBLEMS_PER_PAGE']*(page-1))

app/templates/contest/add_topic.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Contest{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Contest list </div>
                <div class="panel-body">
                     <div class="contest-main">
                            <h1>{{ contest.title }}<br></h1>
                            <h4>开始于：<span class="label label-success">{{ contest.start_time }}</span> 结束于：<span class="label label-danger">{{ contest.end_time }}</span> <span class="label label-info">public</span></h4>
                            <ul class="nav nav-pills" id="contest-nav">
                                <li class="active"><a href="{{ url_for('contest.show', cid=contest.id) }}">题目</a></li>
                                <li><a href="{{ url_for('contest.rank', cid=contest.id) }}">排名</a></li>
                                <li><a href="{{ url_for('contest.static', cid=contest.id) }}">统计</a></li>
                                <li><a href="{{ url_for('contest.status', cid=contest.id) }}">状态</a></li>
                                <li><a href="{{ url_for('contest.topics', cid=contest.id) }}">答疑</a></li>
                            </ul>
                            <hr>
                         <div id="add_topic">
                            {{ wtf.quick_form(form) }}
                         </div>

                         </div>





                </div>
            </div>
        </div>

    </div>
</div>


<!--{% for contest in contests %}-->
<!--<a href="{{ url_for('contest.show', cid=contest.id) }}">{{ contest.title }}</a><br>-->
<!--{% endfor %}-->

{% endblock %}

app/templates/contest/contest.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Contest{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Contest list </div>
                <div class="panel-body">
                     <div class="contest-main">
                            <h1>{{ contest.title }}<br></h1>
                            <h4>开始于：<span class="label label-success">{{ contest.start_time }}</span> 结束于：<span class="label label-danger">{{ contest.end_time }}</span> <span class="label label-info">{{ macros.contest_status(contest) }}</span></h4>
                            <ul class="nav nav-pills" id="contest-nav">
                                <li class="active"><a href="{{ url_for('contest.show', cid=contest.id) }}">题目</a></li>
                                <li><a href="{{ url_for('contest.rank', cid=contest.id) }}">排名</a></li>
                                <!--<li><a href="{{ url_for('contest.static', cid=contest.id) }}">统计</a></li>-->
                                <li><a href="{{ url_for('contest.status', cid=contest.id) }}">状态</a></li>
                                <li><a href="{{ url_for('contest.topics', cid=contest.id) }}">答疑</a></li>
                            </ul>
                            <hr>
                         {% if contest.status == 0 %}
                            <h1>Contest not started</h1>
                         {% else %}
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th width="20%">题号</th>
                                    <th width="80%">题目标题</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for problem in contest.problems %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td><a href="{{ url_for('contest.show_problem', cid=contest.id, pid=problem.id) }}">{{ problem.title }}</a></td>
                                </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                         {% endif %}


                        </div>
                </div>
            </div>
        </div>

    </div>
</div>


<!--{% for contest in contests %}-->
<!--<a href="{{ url_for('contest.show', cid=contest.id) }}">{{ contest.title }}</a><br>-->
<!--{% endfor %}-->

{% endblock %}

app/templates/contest/status.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Contest{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Contest list </div>
                <div class="panel-body">
                     <div class="contest-main">
                            <h1>{{ contest.title }}<br></h1>
                            <h4>开始于：<span class="label label-success">{{ contest.start_time }}</span> 结束于：<span class="label label-danger">{{ contest.end_time }}</span> <span class="label label-info">{{ macros.contest_status(contest) }}</span></h4>
                            <ul class="nav nav-pills" id="contest-nav">
                                <li><a href="{{ url_for('contest.show', cid=contest.id) }}">题目</a></li>
                                <li><a href="{{ url_for('contest.rank', cid=contest.id) }}">排名</a></li>
                                <!--<li><a href="{{ url_for('contest.static', cid=contest.id) }}">统计</a></li>-->
                                <li class="active"><a href="{{ url_for('contest.status', cid=contest.id) }}">状态</a></li>
                                <li><a href="{{ url_for('contest.topics', cid=contest.id) }}">答疑</a></li>
                            </ul>
                            <hr>

                         <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>编号</th>
                                    <th>题号</th>
                                    <th>用户</th>
                                    <th>结果</th>
                                    <th>耗时</th>
                                    <th>内存</th>
                                    <th>语言</th>
                                    <th>长度</th>
                                    <th>时间</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for submission in submissions %}
                            <tr>
                                <th scope="row">{{ submission.id }}</th>
                                <td><a href="{{ url_for('problem.show', id=submission.problem.id) }}">{{ submission.problem.id }}</a></td>
                                <td>{{ submission.user.username }}</td>
                                <td>
                                    {{ macros.submission_result(submission) }}

                                </td>
                                <td>{{ submission.time }}</td>
                                <td>{{ submission.memory }}</td>
                                {% if not current_user.is_authenticated %}
                                <td>{{ macros.submission_language(submission) }}</td>
                                {% elif submission.user == current_user or current_user.is_administrator %}
                                <td><a href="{{ url_for('problem.show_code', id=submission.id) }}">{{ macros.submission_language(submission) }}</a></td>
                                {% else %}
                                <td>{{ macros.submission_language(submission) }}</td>
                                {% endif %}
                                <td>{{ submission.code_length }}</td>
                                <td>{{ submission.create_time }}</td>
                            </tr>

                            {% endfor %}

                                </tbody>
                            </table>
                         <div class="row">
                        <nav>
                            {% if pagination %}
                            <div class="pagination">
                                {{ macros.pagination_widget(pagination, 'contest.status', cid=contest.id) }}
                            </div>
                            {% endif %}
                        </nav>
                    </div>





                </div>
            </div>
        </div>

    </div>
</div>


<!--{% for contest in contests %}-->
<!--<a href="{{ url_for('contest.show', cid=contest.id) }}">{{ contest.title }}</a><br>-->
<!--{% endfor %}-->

{% endblock %}

app/templates/contest/topics.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Contest{% endblock %}

{% block page_content %}

<div class="container content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Contest list</div>
                <div class="panel-body">
                    <div class="contest-main">
                        <h1>{{ contest.title }}<br></h1>
                        <h4>开始于：<span class="label label-success">{{ contest.start_time }}</span> 结束于：<span
                                class="label label-danger">{{ contest.end_time }}</span> <span class="label label-info">{{ macros.contest_status(contest) }}</span>
                        </h4>
                        <ul class="nav nav-pills" id="contest-nav">
                            <li><a href="{{ url_for('contest.show', cid=contest.id) }}">题目</a></li>
                            <li><a href="{{ url_for('contest.rank', cid=contest.id) }}">排名</a></li>
                            <!--<li><a href="{{ url_for('contest.static', cid=contest.id) }}">统计</a></li>-->
                            <li><a href="{{ url_for('contest.status', cid=contest.id) }}">状态</a></li>
                            <li class="active"><a href="{{ url_for('contest.topics', cid=contest.id) }}">答疑</a></li>
                        </ul>
                        <hr>
                        <div class="row" >
                        <div class="form-group form-inline" style="text-align=left; float:left; margin-left:10px;">
                            <label for="problem_id">ID:</label>
                            <input class="form-control" id="problem_id">
                            <label for="problem_name">NAME:</label>
                            <input class="form-control" id="problem_name">
                            <button class="btn btn-default" type="submit">Search</button>
                        </div>
                            <button class="btn btn-primary" style="text-align=left; float:right; margin-right:30px;"><a href="{{ url_for('contest.add_topic', cid=contest.id) }}" style="color:#FCF8E3;">提问</a></button>

                    </div>
                        <div class="contest-topics">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th class="col-sm-1">题号</th>
                                    <th>标题</th>
                                    <th class="col-sm-2">作者</th>
                                </tr>
                                </thead>
                                <tbody>
                                 {% for topic in contest.topics %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('contest.show_problem', cid=contest.id, pid=topic.contest_problem_id) }}" style="color: #000000"> {{ "%c" | format( 64 + topic.contest_problem_id) }}</a></td>
                                    <td>
                                        <a href="{{ url_for('contest.show_topic', cid=contest.id, tid=topic.id) }}"><strong>{{ topic.title }}</strong></a>
                                    </td>
                                    <td><a href="{{ url_for('account.show', id=topic.user.id) }}">{{ topic.user.username }}</a></td>
                                </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            </div>

        </div>
    </div>


    {% endblock %}