app/status/__init__.py
from flask import Blueprint

status = Blueprint('status', __name__)

from . import views, forms

app/status/views.py
from flask import render_template, redirect, request, url_for, flash, current_app
from flask.ext.login import current_user
from . import status
from .. import db
from ..models import User, Submission, News


@status.route('/', methods=['GET', 'POST'])
def list():
    page = request.args.get('page', 1, type=int)
    pagination = Submission.query.order_by(Submission.create_time.desc()).paginate(
        page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
        error_out=False
    )
    submissions = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('status/list.html', submissions=submissions, pagination=pagination, newslist=newslist)


@status.route('/search', methods=['GET', 'POST'])
def search():
    page = request.args.get('page', 1, type=int)
    problem_id = request.args.get('problem_id', 0, type=int)
    author = request.args.get('author', '')
    language = request.args.get('language', 0, type=int)
    status = request.args.get('status', 0, type=int)
    print "problem_id == ", problem_id
    pagination = Submission.query
    if problem_id != 0:
        print 111111
        pagination = pagination.filter_by(problem_id=problem_id)
    if (author != None) and (author != ''):
        print 22222
        user = User.query.filter_by(username=author).first()
        pagination = pagination.filter_by(user=user)
    if language != 0:
        print 33333
        pagination = pagination.filter_by(language=language-1)
    if status != 0:
        print 44444
        pagination = pagination.filter_by(result=status-1)

    pagination = pagination.order_by(Submission.create_time.desc()).paginate(
        page, per_page=current_app.config['OJ_PROBLEMS_PER_PAGE'],
        error_out=False
    )
    submissions = pagination.items
    newslist = News.query.filter_by(is_show=True).filter_by(is_delete=False).order_by(News.id.desc())
    return render_template('status/search_list.html', submissions=submissions, pagination=pagination, newslist=newslist)

app/templates/status/code.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Status{% endblock %}

{% block page_content %}
<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Code</div>
                <div class="panel-body">
                    <div id="editor" name="editor">{{ submission.code }}</div>
                    <script>
                           var editor = ace.edit("editor");
                           editor.getSession().setMode("ace/mode/c_cpp");
                           editor.setReadOnly(true);

                    </script>

                    {% if submission.result == 9 %}
                    <hr>
                    <h3>Compile Error info</h3>
                    <pre>{{ submission.info }}</pre>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}

app/templates/status/list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Status{% endblock %}

{% block page_content %}
<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Status</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group form-inline">
                            <form name="search_form" method="get" action="{{ url_for('status.search') }}">
                                <label >problem id:</label>
                                <input class="form-control" name="problem_id" id="problem_id" style="width:10%;"/>
                                <label >Author:</label>
                                <input class="form-control" name="author" id="author" style="width:10%;"/>
                                <label >Language:</label>
                                <select class="form-control" id="language" name="language">
                                    <option selected="" value="0">All</option>
                                    <option value="1">C</option>
                                    <option value="2">C++</option>
                                    <option value="3">JAVA</option>
                                </select>
                                <label >Status:</label>
                                <select class="form-control" id="status" name="status">
                                    <option selected="" value="0">All</option>
                                    <option value="1">Waiting</option>
                                    <option value="2">Runing</option>
                                    <option value="3">Accepted</option>
                                    <option value="4">Presentation Error</option>
                                    <option value="5">Wrong Answer</option>
                                    <option value="6">Time Limit Exceeded</option>
                                    <option value="7">Memory Limit Exceeded</option>
                                    <option value="8">Output Limit Exceeded</option>
                                    <option value="9">Compile Error</option>
                                    <option value="10">System Error</option>
                                </select>

                                <button class="btn btn-default" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th width="10%">Problem id</th>
                                <th width="10%">User</th>
                                <th width="10%">Result</th>
                                <th width="10%">Time</th>
                                <th width="10%">Memory</th>
                                <th width="10%">Language</th>
                                <th width="10%">Length</th>
                                <th width="20%">Time</th>
                            </tr>
                            </thead>
                            <tbody>


                            {% for submission in submissions %}
                            <tr>
                                <th scope="row">{{ submission.id }}</th>
                                <td><a href="{{ url_for('problem.show', id=submission.problem.id) }}">{{ submission.problem.id }}</a></td>
                                <td>{{ submission.user.username }}</td>
                                <td>
                                    {{ macros.submission_result(submission) }}
                                </td>
                                <td>{{ submission.time }}</td>
                                <td>{{ submission.memory }}</td>
                                {% if not current_user.is_authenticated %}
                                <td>{{ macros.submission_language(submission) }}</td>
                                {% elif submission.user == current_user or current_user.is_administrator %}
                                <td><a href="{{ url_for('problem.show_code', id=submission.id) }}">{{ macros.submission_language(submission) }}</a></td>
                                {% else %}
                                <td>{{ macros.submission_language(submission) }}</td>
                                {% endif %}
                                <td>{{ submission.code_length }}</td>
                                <td>{{ submission.create_time }}</td>
                            </tr>

                            {% endfor %}


                            </tbody>
                        </table>
                        <!-- <hr> -->
                    </div>
                    <div class="row">
                        <nav>
                            {% if pagination %}
                            <div class="pagination">
                                {{ macros.pagination_widget(pagination, 'status.list') }}
                            </div>
                            {% endif %}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}

app/templates/status/search_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Status{% endblock %}

{% block page_content %}
<div class="container content">
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">Status</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group form-inline">
                            <form name="search_form" method="get" action="{{ url_for('status.search') }}">
                                <label >problem id:</label>
                                <input class="form-control" name="problem_id" id="problem_id" style="width:10%;"/>
                                <label >Author:</label>
                                <input class="form-control" name="author" id="author" style="width:10%;"/>
                                <label >Language:</label>
                                <select class="form-control" id="language" name="language">
                                    <option selected="" value="0">All</option>
                                    <option value="1">C</option>
                                    <option value="2">C++</option>
                                    <option value="3">JAVA</option>
                                </select>
                                <label >Status:</label>
                                <select class="form-control" id="status" name="status">
                                    <option selected="" value="0">All</option>
                                    <option value="1">Waiting</option>
                                    <option value="2">Runing</option>
                                    <option value="3">Accepted</option>
                                    <option value="4">Presentation Error</option>
                                    <option value="5">Wrong Answer</option>
                                    <option value="6">Time Limit Exceeded</option>
                                    <option value="7">Memory Limit Exceeded</option>
                                    <option value="8">Output Limit Exceeded</option>
                                    <option value="9">Compile Error</option>
                                    <option value="10">System Error</option>
                                </select>

                                <button class="btn btn-default" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th width="10%">ID</th>
                                <th width="10%">Problem id</th>
                                <th width="10%">User</th>
                                <th width="10%">Result</th>
                                <th width="10%">Time</th>
                                <th width="10%">Memory</th>
                                <th width="10%">Language</th>
                                <th width="10%">Length</th>
                                <th width="20%">Time</th>
                            </tr>
                            </thead>
                            <tbody>


                            {% for submission in submissions %}
                            <tr>
                                <th scope="row">{{ submission.id }}</th>
                                <td><a href="{{ url_for('problem.show', id=submission.problem.id) }}">{{ submission.problem.id }}</a></td>
                                <td>{{ submission.user.username }}</td>
                                <td>
                                    {{ macros.submission_result(submission) }}
                                </td>
                                <td>{{ submission.time }}</td>
                                <td>{{ submission.memory }}</td>
                                {% if submission.user == current_user or current_user.is_administrator %}
                                <td><a href="{{ url_for('problem.show_code', id=submission.id) }}">{{ macros.submission_language(submission) }}</a></td>
                                {% else %}
                                <td>{{ macros.submission_language(submission) }}</td>
                                {% endif %}
                                <td>{{ submission.code_length }}</td>
                                <td>{{ submission.create_time }}</td>
                            </tr>

                            {% endfor %}


                            </tbody>
                        </table>
                        <!-- <hr> -->
                    </div>
                    <div class="row">
                        <nav>
                            {% if pagination %}
                            <div class="pagination">
                                {{ macros.pagination_widget(pagination, 'status.search', problem_id=request.args['problem_id'], author=request.args['author'], language=request.args['language'], status=request.args['status']) }}
                            </div>
                            {% endif %}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            {{ macros.userpanel(current_user) }}
            {{ macros.newspanel(newslist) }}
        </div>
    </div>
</div>


{% endblock %}